WorkflowConfigs:


  - workflowCode: WF_A_AL
    type: ASYNC
    description: Aligns the input files. 
    useCase: A_A
    sequence:
    - order: 0
      tool:
      - name: ALIGNER
        description: Accepts 2 parallel files and alings them into parallel corp for training
        kafka-input:
        - topic: anuvaad-dp-tools-aligner-input-v3
          partitions: 2
          keys: aligner-input-key-one, aligner-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-aligner-output-v3
          partitions: 2
          keys: aligner-output-key-one, aligner-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: WF_A_FC
    type: ASYNC
    description: converts a file into pdf and other formats
    useCase: A_F
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: WF_A_BM
    type: ASYNC
    description: extracts different blocks from a pdf file.
    useCase: A_B
    sequence:
    - order: 0
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: WF_A_FCBM
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks.
    useCase: A_FB
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true


  - workflowCode: WF_A_FCBMTK
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks. Text content of each block is tokenised.
    useCase: A_FBT
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input-v1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output-v1
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: WF_A_FCBMTKTR
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks. Text content of each block is tokenised and translated
    useCase: A_FBTTR
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input-v1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output-v1
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 3
      tool:
      - name: TRANSLATOR
        description: Translates sentences from a bm-tok processed json file.
        kafka-input:
        - topic: anuvaad-dp-tools-translator-input-v3
          partitions: 2
          keys: anuvaad-dp-tools-translator-input-key-one, anuvaad-dp-tools-translator-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-translator-output-v3
          partitions: 2
          keys: anuvaad-dp-tools-translator-output-key-one, anuvaad-dp-tools-translator-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: WF_A_FCWDLD
    type: ASYNC
    description: converts file into pdf and then detects words and layouts using CV.
    useCase: A_FWL
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output-v1
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: WORD-DETECTOR
        description: detects word blocks from a given file
        kafka-input:
        - topic: anuvaad-dp-tools-word-detector-craft-input-v1
          partitions: 2
          keys: anuvaad-dp-tools-word-detector-craft-input-key-one, anuvaad-dp-tools-word-detector-craft-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-word-detector-craft-output-v1
          partitions: 2
          keys: anuvaad-dp-tools-word-detector-craft-output-key-one, anuvaad-dp-tools-word-detector-craft-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: LAYOUT-DETECTOR
        description: detects layouts from a given file
        kafka-input:
        - topic: anuvaad-dp-tools-layout-detector-prima-input-v1
          partitions: 2
          keys: anuvaad-dp-tools-layout-detector-prima-input-key-one, anuvaad-dp-tools-layout-detector-prima-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-layout-detector-prima-output-v1
          partitions: 2
          keys: anuvaad-dp-tools-layout-detector-prima-output-key-one, anuvaad-dp-tools-layout-detector-prima-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: WF_S_TR
    type: SYNC
    description: Translates the sentences.
    useCase: S_TR
    sequence:
    - order: 0
      tool:
      - name: TRANSLATOR
        description: Translates the sentences.
        api-details:
        - uri: http://gateway_anuvaad-etl-translator:5001/anuvaad-etl/translator/v1/block/workflow/translate
      endState: true



  - workflowCode: WF_S_TKTR
    type: SYNC
    description: Tokenises the text blocks to sentences and Translates them.
    useCase: S_TTR
    sequence:
    - order: 0
      tool:
      - name: TOKENISER
        description: tokenises the text blocks.
        api-details:
        - uri: http://gateway_anuvaad-etl-tokeniser:5001/api/v0/blocks-tokenisation-wf
      endState: false
    - order: 1
      tool:
      - name: TRANSLATOR
        description: Translates the sentences.
        api-details:
        - uri: http://gateway_anuvaad-etl-translator:5001/anuvaad-etl/translator/v1/block/workflow/translate
      endState: true


# Conventions:
# WF - prefix for Workflow
# A - type of workflow: ASYNC
# S - type of workflow: SYNC
# AL,A - tool: Aligner
# FC,F - tool: File Converter
# BM,B - tool: Block Merger
# TK,T - tool: Tokeniser
# TR - tool: Translator