WorkflowConfigs:


  - workflowCode: DP_WFLOW_FB
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks.
    useCase: FC-BM
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_FC_INPUT_V1
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_FC_OUTPUT_V1
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_BLOCK_MERGER_INPUT_V2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_BLOCK_MERGER_OUTPUT_V2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true


  - workflowCode: DP_WFLOW_FBT
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks. Text content of each block is tokenised.
    useCase: FC-BM-TOK
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_FC_INPUT_V1
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_FC_OUTPUT_V1
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_BLOCK_MERGER_INPUT_V2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_BLOCK_MERGER_OUTPUT_V2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_TOKENISER_INPUT_V1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_TOKENISER_OUTPUT_V1
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_FBTTR
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks. Text content of each block is tokenised and translated
    useCase: FC-BM-TOK-TRANS
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_FC_INPUT_V1
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_FC_OUTPUT_V1
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_BLOCK_MERGER_INPUT_V2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_BLOCK_MERGER_OUTPUT_V2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_TOKENISER_INPUT_V1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_TOKENISER_OUTPUT_V1
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 3
      tool:
      - name: TRANSLATOR
        description: Translates sentences from a bm-tok processed json file.
        kafka-input:
        - topic: ANUVAAD_DP_TOOLS_TRANSLATOR_INPUT_V2
          partitions: 2
          keys: anuvaad-dp-tools-translator-input-key-one, anuvaad-dp-tools-translator-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: ANUVAAD_DP_TOOLS_TRANSLATOR_OUTPUT_V2
          partitions: 2
          keys: anuvaad-dp-tools-translator-output-key-one, anuvaad-dp-tools-translator-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_S_TR
    type: SYNC
    description: Translates the sentences.
    useCase: S_TR
    sequence:
    - order: 0
      tool:
      - name: TRANSLATOR
        description: Translates the sentences.
        api-details:
        - uri: http://user_anuvaad-etl-translator:5004/anuvaad-etl/translator/v1/block/workflow/translate
      endState: true



  - workflowCode: DP_WFLOW_S_TTR
    type: SYNC
    description: Tokenises the text blocks to sentences and Translates them.
    useCase: S_TTR
    sequence:
    - order: 0
      tool:
      - name: TOKENISER
        description: tokenises the text blocks.
        api-details:
        - uri: http://user_anuvaad-etl-tokeniser:5001/api/v0/blocks-tokenisation-wf
      endState: false
    - order: 1
      tool:
      - name: TRANSLATOR
        description: Translates the sentences.
        api-details:
        - uri: http://user_anuvaad-etl-translator:5004/anuvaad-etl/translator/v1/block/workflow/translate
      endState: true



  - workflowCode: DP_WFLOW_S_C
    type: SYNC
    description: 
    useCase: S_C
    sequence:
    - order: 0
      tool:
      - name: CONTENT-HANDLER
        description: Saves Blocks to CH.
        api-details:
        - uri: http://user_anuvaad-content-handler:5001/api/v0/update-content
      endState: true



  - workflowCode: DP_WFLOW_S_IT_T
    type: SYNC
    description: Serves Interactive Translation through translator service
    useCase: S_IT_T
    sequence:
    - order: 0
      tool:
      - name: TRANSLATOR
        description: Translates the given text
        api-details:
        - uri: http://user_anuvaad-etl-translator:5004/anuvaad-etl/translator/v1/text/workflow/translate
      endState: true