WorkflowConfigs:


  - workflowCode: DP_WFLOW_T
    type: ASYNC
    description: tokenises paragraphs into sentences.    
    useCase: TOK
    sequence:
    - order: 0
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_A
    type: ASYNC
    description: Aligns the input files. 
    useCase: ALIGN
    sequence:
    - order: 0
      tool:
      - name: ALIGNER
        description: Accepts 2 parallel files and alings them into parallel corp for training
        kafka-input:
        - topic: anuvaad-dp-tools-aligner-input-v2
          partitions: 2
          keys: aligner-input-key-one, aligner-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-aligner-output-v2
          partitions: 2
          keys: aligner-output-key-one, aligner-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_TA
    type: ASYNC
    description: tokenises into sentences, aligns the corp.    
    useCase: TOK-ALIGN
    sequence:
    - order: 0
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: ALIGNER
        description: Accepts 2 parallel files and alings them into parallel corp for training
        kafka-input:
        - topic: anuvaad-dp-tools-aligner-input-v2
          partitions: 2
          keys: aligner-input-key-one, aligner-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-aligner-output-v2
          partitions: 2
          keys: aligner-output-key-one, aligner-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_P2H
    type: ASYNC
    description: Converts a pdf into html and image files.    
    useCase: P2H
    sequence:
    - order: 0
      tool:
      - name: PDFTOHTML
        description: Converts a pdf into html and image files
        kafka-input:
        - topic: anuvaad-dp-tools-pdf-html-input
          partitions: 2
          keys: pdf-html-input-key-one, pdf-html-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-pdf-html-output
          partitions: 2
          keys: pdf-html-output-key-one, pdf-html-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_P2H2J
    type: ASYNC
    description: Converts a pdf into json.  
    useCase: P2H-H2J
    sequence:
    - order: 0
      tool:
      - name: PDFTOHTML
        description: Converts a pdf into html and image files
        kafka-input:
        - topic: anuvaad-dp-tools-pdf-html-input
          partitions: 2
          keys: pdf-html-input-key-one, pdf-html-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-pdf-html-output
          partitions: 2
          keys: pdf-html-output-key-one, pdf-html-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: HTMLTOJSON
        description: Converts a html files to json
        kafka-input:
        - topic: anuvaad-dp-tools-html-json-input
          partitions: 2
          keys: html-json-input-key-one, html-json-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-html-json-output
          partitions: 2
          keys: html-json-output-key-one, html-json-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_F
    type: ASYNC
    description: converts a file into pdf and other formats
    useCase: FC
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_B
    type: ASYNC
    description: extracts different blocks from a pdf file.
    useCase: BM
    sequence:
    - order: 0
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_FB
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks.
    useCase: FC-BM
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_BT
    type: ASYNC
    description: extracts multiple blocks, Text content of each block is tokenised.
    useCase: BM-TOK
    sequence:
    - order: 0
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_FBT
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks. Text content of each block is tokenised.
    useCase: FC-BM-TOK
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_TR
    type: ASYNC
    description: Translates sentences from a bm-tok processed json file.
    useCase: TRANS
    sequence:
    - order: 0
      tool:
      - name: TRANSLATOR
        description: Translates sentences from a bm-tok processed json file.
        kafka-input:
        - topic: anuvaad-dp-tools-translator-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-translator-input-key-one, anuvaad-dp-tools-translator-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-translator-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-translator-output-key-one, anuvaad-dp-tools-translator-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_FBTTR
    type: ASYNC
    description: converts file into pdf and then extracts multiple blocks. Text content of each block is tokenised and translated
    useCase: FC-BM-TOK-TRANS
    sequence:
    - order: 0
      tool:
      - name: FILE-CONVERTER
        description: converts a file into pdf and other formats.
        kafka-input:
        - topic: anuvaad-dp-tools-fc-input
          partitions: 2
          keys: anuvaad-dp-tools-fc-input-key-one, anuvaad-dp-tools-fc-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-fc-output
          partitions: 2
          keys: anuvaad-dp-tools-fc-output-key-one, anuvaad-dp-tools-fc-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 3
      tool:
      - name: TRANSLATOR
        description: Translates sentences from a bm-tok processed json file.
        kafka-input:
        - topic: anuvaad-dp-tools-translator-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-translator-input-key-one, anuvaad-dp-tools-translator-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-translator-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-translator-output-key-one, anuvaad-dp-tools-translator-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true


  
  - workflowCode: DP_WFLOW_BTTR
    type: ASYNC
    description: extracts multiple blocks. Text content of each block is tokenised and translated
    useCase: BM-TOK-TRANS
    sequence:
    - order: 0
      tool:
      - name: BLOCK-MERGER
        description: extracts different blocks from a pdf file.
        kafka-input:
        - topic: anuvaad-dp-tools-block-merger-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-input-key-one, anuvaad-dp-tools-block-merger-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-block-merger-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-block-merger-output-key-one, anuvaad-dp-tools-block-merger-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TRANSLATOR
        description: Translates sentences from a bm-tok processed json file.
        kafka-input:
        - topic: anuvaad-dp-tools-translator-input-v2
          partitions: 2
          keys: anuvaad-dp-tools-translator-input-key-one, anuvaad-dp-tools-translator-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-translator-output-v2
          partitions: 2
          keys: anuvaad-dp-tools-translator-output-key-one, anuvaad-dp-tools-translator-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



  - workflowCode: DP_WFLOW_S_T
    type: SYNC
    description: Tokenises the given list of text blocks.
    useCase: S_T
    sequence:
    - order: 0
      tool:
      - name: TOKENISER
        description: tokenises the text blocks.
        api-details:
        - uri: http://gateway_anuvaad-etl-tokeniser:5001/api/v0/blocks-tokenisation-wf
      endState: true



  - workflowCode: DP_WFLOW_S_TR
    type: SYNC
    description: Translates the sentences.
    useCase: S_TR
    sequence:
    - order: 0
      tool:
      - name: TRANSLATOR
        description: Translates the sentences.
        api-details:
        - uri: http://gateway_anuvaad-etl-translator:5004/anuvaad-etl/translator/v1/doc/workflow/translate
      endState: true


  - workflowCode: DP_WFLOW_S_TTR
    type: SYNC
    description: Tokenises the text blocks to sentences and Translates them.
    useCase: S_TTR
    sequence:
    - order: 0
      tool:
      - name: TOKENISER
        description: tokenises the text blocks.
        api-details:
        - uri: http://gateway_anuvaad-etl-tokeniser:5001/api/v0/blocks-tokenisation-wf
      endState: false
    - order: 1
      tool:
      - name: TRANSLATOR
        description: Translates the sentences.
        api-details:
        - uri: http://gateway_anuvaad-etl-translator:5004/anuvaad-etl/translator/v1/doc/workflow/translate
      endState: ]true